unbind r 
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set-option -g default-shell /bin/zsh
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:Cc=\E]12;%p1%s\a,xterm-kitty:Cr=\E]112\a"
set -as terminal-features ",xterm-kitty:RGB"


# control s is the leader now :)
set -g prefix C-s
set -g mouse on

# VIM motions inside tmux
setw -g mode-keys vi 
bind-key h select-pane -L 
bind-key j select-pane -D 
bind-key k select-pane -U
bind-key k select-pane -R

# Listing Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

# INformation into the status bar 
set -g @dracula-show-powerline true
set -g @dracula-fixed-location "vrindavan"
set -g @dracula-plugins "weather"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g status-position top

# Initialize the TMUX config file
run '~/.tmux/plugins/tpm/tpm'
